### ISSUE TITLE
Обучение распознавания

### ISSUE THREAD

**Issue by miksherfast** [ria-com/nomeroff-net#224]
Добрый день.
 
Можете помочь с обучение базы распознавания русских прямоугольных номеров (https://github.com/ria-com/nomeroff-net/tree/v2.5) 
Месяц уже биюсь с этим вопросом ни как не получается по описаниям https://habr.com/ru/post/439330/ запустить обучение.
Проект удалось запустить в виртуальной машине на Debian
 
После запуска ru-train.ipynb (отличие от ocr-ru-train.ipynb в строке «from NomeroffNet.TextDetectors.base.ocr import OCR»)
Выдает лог в файле во вложении log.log
[log.log](https://github.com/ria-com/nomeroff-net/files/8855336/log.log)

**Comment by ApelSYN** [comment]
1. У Вас там написано что система не находит GPU: "GPUAccelerator can not run on your system since the accelerator is not available."
2. Мы сейчас не производим никаких доработок по русской модели или для пользователей РФ по причине окупации части террирорий Украины армией РФ. Каждый день идут обстелы мирных городов и звучат воздушные тревоги во всех городах Украины. Все разработчики нашей команды сейчас проживают в Украине, часть из нас были вынуждены переселять свои семьи, так как их города окупированы и разграблены армией РФ. 
3. Тренировать двухлинейные номера бессмыслено, т. к. наши модели адаптированы для чтения 1 линейной строки, в репозитории есть примеры частичного решения этой проблемы, когда двухлинейная строка преобразовывается в однолинейную и после этого распознается. Это работает хуже чем с обычным номером, но работает.
