### ISSUE TITLE
Performance question

### ISSUE THREAD

**Issue by gasparuff** [ria-com/nomeroff-net#290]
Hello,

I'm running this project on a Raspberry Pi4 with 4GB of RAM and it works actually quite well. I'm testing with a bunch of photos I took many years ago and the detection works. Although it takes between 5-10 seconds for detecting the license plate and returning the result. Although sometimes the RPi just "dies" when I execute the detection too many times, I guess the hardware is just reaching it's limits (overheating?). 

Is there anything I can do to improve this? I'm thinking in the direction of sacrificing quality for speed. For the particular case I want to solve, I will always get just one photo in very good quality and the license plate will always be approximately in the same region of the photo. 

What are my options?

PS: Thanks to all of you for putting together such an awesome project, that allows me to run ANPR without almost any knowledge about ML. Although I'm digging into the whole topic to get a better understanding of everything, it will take me some more time until I get the full picture :).

**Comment by dimabendera** [comment]
Hello,

It’s great to hear that the project is running on your Raspberry Pi 4 and delivering good results despite the hardware limitations. Here are some suggestions to improve performance and prevent your RPi from “dying” during extended usage:

Use a Tiny Nomeroff-Net:
Check out the tiny demo of Nomeroff-Net here:
[Nomeroff-Net Tiny Demo](https://github.com/ria-com/nomeroff-net/blob/master/tutorials/ju/inference/get-started-tiny-demo.ipynb).
This demo is specifically designed for devices with limited hardware.

Train Smaller YOLO Models:
Consider training smaller YOLO models, such as YOLOv5, YOLOv8-n or YOLOv11-n, that are optimized for speed and efficiency. These models can still deliver acceptable accuracy while requiring less computation.

Convert Models to NCNN Format:
Optimize your models by converting them to NCNN format, which is designed for edge devices like Raspberry Pi. This can significantly reduce processing times.
[Convert YOLO to NCNN format](https://docs.ultralytics.com/guides/raspberry-pi/#use-ncnn-on-raspberry-pi)

Add Hardware Acceleration with Coral Edge TPU:
If you need better performance, consider adding a Coral USB Accelerator or an Edge TPU for the Raspberry Pi. These accelerators can offload AI computations, speeding up inference times dramatically while reducing CPU and GPU load.

Adjust Model and Input Settings:

Crop the image to include only the region where the license plate is likely to appear, reducing the size of the input image.
Reduce the image resolution while maintaining enough quality for detection.
Optimize Cooling for the Raspberry Pi:
Since overheating might be an issue, consider using a cooling solution such as a fan or heat sink. This can help the RPi sustain performance during extended workloads.
