### ISSUE TITLE
Wrong link for OCR dataset

### ISSUE THREAD

**Issue by yehorchernenko** [ria-com/nomeroff-net#50]
Please provide actual link for UA OCR dataset because it wrong 
https://nomeroff.net.ua/datasets/autoriaNumberplateOcrUa-2019-02-19.zip

**Comment by ApelSYN** [comment]
Hello, Yehor!

We really do not have time to quickly update links to fresh datasets. A list of the latest versions of all datasets is available via the link https://nomeroff.net.ua/datasets/.
We divided the Ukrainian dataset into two groups, this is due to the different design of license plates, at different periods of their issuance to car owners.
Here are direct links to these two groups:
https://nomeroff.net.ua/datasets/autoriaNumberplateOcrUa-2019-07-30.zip
https://nomeroff.net.ua/datasets/autoriaNumberplateOcrUa-1995-2019-07-30.tar.gz
